//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Whee.WordBuilder.Model;

namespace Whee.WordBuilder.UIHelpers
{
	public interface IResultViewHelper
	{
		void Clear();
		void AddItem(Context context);
		List<Context> GetSelectedItems();
		List<Context> GetAllItems();
		event EventHandler<EventArgs> SelectionChanged;
	}
}
