//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Whee.WordBuilder.UIHelpers
{
	public interface ITextViewHelper
	{
		void Clear();
		void OnDocumentChanged(Object sender, string newText);
		void GotoLine(int linenumber);
		event EventHandler<Whee.WordBuilder.Model.Events.DocumentChangedEventArgs> BufferChanged;
	}
}
