//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Whee.WordBuilder.ProjectV2;

namespace Whee.WordBuilder.UIHelpers
{
    public interface IWarningViewHelper
    {
        void Clear();
        void AddWarning(IProjectNode node, string message);
        bool HasWarnings { get; }
        event EventHandler<WarningEventArgs> WarningActivated;
    }
}
