//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Whee.WordBuilder.Model.Events;
using Whee.WordBuilder.Helpers;

namespace Whee.WordBuilder.Model
{


	public class Document
	{
		public Document ()
		{
			Dirty = false;
		}
		
		public Document (string initialText)
		{
			m_Text = initialText;
			Dirty = false;
		}
		
		private string m_Text;
		public string Text
		{ 
			get { return m_Text; }
			set 
			{ 
				m_Text = value;
				Dirty = true;
				if (DocumentChanged != null)
				{
					DocumentChanged.Invoke(this, new DocumentChangedEventArgs(m_Text));
				}
			}
		}
		
		public event EventHandler<DocumentChangedEventArgs> DocumentChanged;
		
		public string FileName { get; set; }
		
		public bool Dirty { get; private set; }
		
		public void Save(IFileSystem fs)
		{
			fs.WriteAllText(FileName, Text);
			Dirty = false;
		}
		
		public void Load(IFileSystem fs)
		{
			Text = fs.ReadAllText(FileName);
			Dirty = false;
		}
	}
}
