//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NUnit.Framework;
using NSubstitute;
using System;
using Whee.WordBuilder.Model;
using Whee.WordBuilder.Helpers;

namespace test
{


	[TestFixture()]
	public class DocumentTest
	{

		[Test()]
		public void TestSave()
		{
			Document dm = new Document();
			dm.Text = "abc";
			
			dm.FileName = @"c:\abc.wordo";
			
			IFileSystem fs = Substitute.For<IFileSystem>();

			dm.Save(fs);

			fs.Received().WriteAllText(@"c:\abc.wordo", "abc");
		}
		
		[Test()]
		public void TestLoad()
		{
			Document dm = new Document();
			
			dm.FileName = @"c:\abc.wordo";
			
			IFileSystem fs = Substitute.For<IFileSystem>();
			
			fs.ReadAllText(@"c:\abc.wordo").Returns("abc");
			
			dm.Load(fs);
			
			fs.Received().ReadAllText(@"c:\abc.wordo");
			
			Assert.AreEqual("abc", dm.Text);
		}		
		
		[Test()]
		public void TestDirty()
		{
			Document dm = new Document();
			Assert.IsFalse(dm.Dirty);
			
			dm.Text = "abc";
			Assert.IsTrue(dm.Dirty);

			dm.FileName = @"c:\abc.wordo";			
			IFileSystem fs = Substitute.For<IFileSystem>();			
			dm.Save(fs);
			
			Assert.IsFalse(dm.Dirty);
			
			dm.Text = "abc2";
			
			Assert.IsTrue(dm.Dirty);
			
			dm.Save(fs);
			
			Assert.IsFalse(dm.Dirty);

			fs.ReadAllText(@"c:\abc.wordo").Returns("abc3");

			dm.Load(fs);

			Assert.AreEqual("abc3", dm.Text);
			Assert.IsFalse(dm.Dirty);			
		}
	}
}
