//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Whee.WordBuilder.Helpers
{


	public class FileSystem : IFileSystem		
	{
		public FileSystem ()
		{
		}

		#region IFileSystem implementation
		public void WriteAllText (string path, string text)
		{
			System.IO.File.WriteAllText(path, text, System.Text.Encoding.UTF8);
		}
		
		
		public string ReadAllText (string path)
		{
			return System.IO.File.ReadAllText(path);
		}
		
		#endregion
	}
}
