//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Whee.WordBuilder.Helpers
{
	public class Random : IRandom
	{
		private static System.Random s_Random = new System.Random();

		public Random ()
		{	
		}

		#region IRandom implementation
		public int Next (int maxValue)
		{
			return s_Random.Next(maxValue);
		}
		
		public int Next (int minValue, int maxValue)
		{
			return s_Random.Next(minValue, maxValue);
		}
		
		public double NextDouble ()
		{
			return s_Random.NextDouble();
		}
		#endregion		
	}
}
