
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action WordsAction;

	private global::Gtk.Action GenerateAction;

	private global::Gtk.Action ClearAndGenerateAction;

	private global::Gtk.Action ClearAction;

	private global::Gtk.Action CopySelectedAction;

	private global::Gtk.Action CopyDescriptionsAction;

	private global::Gtk.Action ExportAction;

	private global::Gtk.VBox mainVBox;

	private global::Gtk.MenuBar mainMenuBar;

	private global::Gtk.VPaned vpaned2;

	private global::Gtk.HPaned mainHPanes;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView codeTextview;

	private global::Gtk.VPaned resultVPanes;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView resultsTreeview;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView detailsTextview;

	private global::Gtk.ScrolledWindow warningsScrolledWindow;

	private global::Gtk.TreeView warningsTreeView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.newAction = new global::Gtk.Action("newAction", global::Mono.Unix.Catalog.GetString("New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
		w1.Add(this.newAction, "<Control>n");
		this.openAction = new global::Gtk.Action("openAction", global::Mono.Unix.Catalog.GetString("Open..."), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open...");
		w1.Add(this.openAction, "<Control>o");
		this.saveAction = new global::Gtk.Action("saveAction", global::Mono.Unix.Catalog.GetString("Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.saveAction, "<Control>s");
		this.saveAsAction = new global::Gtk.Action("saveAsAction", global::Mono.Unix.Catalog.GetString("Save as..."), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as...");
		w1.Add(this.saveAsAction, "<Control><Alt>s");
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.quitAction, null);
		this.WordsAction = new global::Gtk.Action("WordsAction", global::Mono.Unix.Catalog.GetString("Words"), null, null);
		this.WordsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Words");
		w1.Add(this.WordsAction, null);
		this.GenerateAction = new global::Gtk.Action("GenerateAction", global::Mono.Unix.Catalog.GetString("Generate"), null, null);
		this.GenerateAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Generate");
		w1.Add(this.GenerateAction, "<Control>g");
		this.ClearAndGenerateAction = new global::Gtk.Action("ClearAndGenerateAction", global::Mono.Unix.Catalog.GetString("Clear and generate"), null, null);
		this.ClearAndGenerateAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Clear and generate");
		w1.Add(this.ClearAndGenerateAction, "<Control><Alt>g");
		this.ClearAction = new global::Gtk.Action("ClearAction", global::Mono.Unix.Catalog.GetString("Clear"), null, null);
		this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Clear");
		w1.Add(this.ClearAction, "<Control><Alt>l");
		this.CopySelectedAction = new global::Gtk.Action("CopySelectedAction", global::Mono.Unix.Catalog.GetString("Copy selected"), null, null);
		this.CopySelectedAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy selected");
		w1.Add(this.CopySelectedAction, "<Control>j");
		this.CopyDescriptionsAction = new global::Gtk.Action("CopyDescriptionsAction", global::Mono.Unix.Catalog.GetString("Copy descriptions"), null, null);
		this.CopyDescriptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy descriptions");
		w1.Add(this.CopyDescriptionsAction, "<Control><Alt>j");
		this.ExportAction = new global::Gtk.Action("ExportAction", global::Mono.Unix.Catalog.GetString("Export..."), null, null);
		this.ExportAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export...");
		w1.Add(this.ExportAction, "<Control><Alt>e");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("WordBuilder");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVBox = new global::Gtk.VBox();
		this.mainVBox.Name = "mainVBox";
		this.mainVBox.Spacing = 6;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='mainMenuBar'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='WordsAction' action='WordsAction'><menuitem name='GenerateAction' action='GenerateAction'/><menuitem name='ClearAndGenerateAction' action='ClearAndGenerateAction'/><menuitem name='ClearAction' action='ClearAction'/><separator/><menuitem name='CopySelectedAction' action='CopySelectedAction'/><menuitem name='CopyDescriptionsAction' action='CopyDescriptionsAction'/><separator/><menuitem name='ExportAction' action='ExportAction'/></menu></menubar></ui>");
		this.mainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/mainMenuBar")));
		this.mainMenuBar.Name = "mainMenuBar";
		this.mainVBox.Add(this.mainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.mainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.vpaned2 = new global::Gtk.VPaned();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 199;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.mainHPanes = new global::Gtk.HPaned();
		this.mainHPanes.CanFocus = true;
		this.mainHPanes.Name = "mainHPanes";
		this.mainHPanes.Position = 190;
		// Container child mainHPanes.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.codeTextview = new global::Gtk.TextView();
		this.codeTextview.CanFocus = true;
		this.codeTextview.Name = "codeTextview";
		this.GtkScrolledWindow1.Add(this.codeTextview);
		this.mainHPanes.Add(this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.mainHPanes[this.GtkScrolledWindow1]));
		w4.Resize = false;
		// Container child mainHPanes.Gtk.Paned+PanedChild
		this.resultVPanes = new global::Gtk.VPaned();
		this.resultVPanes.CanFocus = true;
		this.resultVPanes.Name = "resultVPanes";
		this.resultVPanes.Position = 127;
		// Container child resultVPanes.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.resultsTreeview = new global::Gtk.TreeView();
		this.resultsTreeview.CanFocus = true;
		this.resultsTreeview.Name = "resultsTreeview";
		this.GtkScrolledWindow.Add(this.resultsTreeview);
		this.resultVPanes.Add(this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.resultVPanes[this.GtkScrolledWindow]));
		w6.Resize = false;
		// Container child resultVPanes.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.detailsTextview = new global::Gtk.TextView();
		this.detailsTextview.CanFocus = true;
		this.detailsTextview.Name = "detailsTextview";
		this.detailsTextview.Editable = false;
		this.detailsTextview.AcceptsTab = false;
		this.GtkScrolledWindow2.Add(this.detailsTextview);
		this.resultVPanes.Add(this.GtkScrolledWindow2);
		this.mainHPanes.Add(this.resultVPanes);
		this.vpaned2.Add(this.mainHPanes);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.vpaned2[this.mainHPanes]));
		w10.Resize = false;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.warningsScrolledWindow = new global::Gtk.ScrolledWindow();
		this.warningsScrolledWindow.Name = "warningsScrolledWindow";
		this.warningsScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child warningsScrolledWindow.Gtk.Container+ContainerChild
		this.warningsTreeView = new global::Gtk.TreeView();
		this.warningsTreeView.CanFocus = true;
		this.warningsTreeView.Name = "warningsTreeView";
		this.warningsScrolledWindow.Add(this.warningsTreeView);
		this.vpaned2.Add(this.warningsScrolledWindow);
		this.mainVBox.Add(this.vpaned2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.vpaned2]));
		w13.Position = 1;
		this.Add(this.mainVBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 538;
		this.DefaultHeight = 411;
		this.warningsScrolledWindow.Hide();
		this.Show();
		this.newAction.Activated += new global::System.EventHandler(this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler(this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler(this.OnSaveActionActivated);
		this.saveAsAction.Activated += new global::System.EventHandler(this.OnSaveAsActionActivated);
		this.quitAction.Activated += new global::System.EventHandler(this.OnQuitActionActivated);
		this.GenerateAction.Activated += new global::System.EventHandler(this.OnGenerateActionActivated);
		this.ClearAndGenerateAction.Activated += new global::System.EventHandler(this.OnClearAndGenerateActionActivated);
		this.ClearAction.Activated += new global::System.EventHandler(this.OnClearActionActivated);
		this.CopySelectedAction.Activated += new global::System.EventHandler(this.OnCopySelectedActionActivated);
		this.CopyDescriptionsAction.Activated += new global::System.EventHandler(this.OnCopyDescriptionsActionActivated);
		this.ExportAction.Activated += new global::System.EventHandler(this.OnExportActionActivated);
	}
}
