//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Whee.WordBuilder.Model.Commands;
using Whee.WordBuilder.ProjectV2;

namespace Whee.WordBuilder.ProjectV2
{
    public class CommandBlockNode : BlockNodeBase
    {
        public CommandBlockNode(IProjectSerializer serializer)
            : base(serializer)
        {
        }

        private List<CommandBase> m_commands = new List<CommandBase>();
        public List<CommandBase> Commands { get { return m_commands; } }

        public override bool LoadSingleItem()
        {
            Token command = m_serializer.ReadTextToken(this);

            if (command != null)
            {
                CommandBase cb = CommandBase.FindCommand(command.Text);

                if (cb != null)
                {
                    command.Type = TokenType.Command;
                    cb.Index = command.Offset;
                    cb.LoadCommand(m_serializer);
                    Commands.Add(cb);
                    Children.Add(cb);
                    //cb.Length = m_serializer.Position - cb.Index;
                    return cb.RequireNewLine;
                }
                else
                {
                    m_serializer.Warn(string.Format("Command '{0}' not found.", command.Text), this);
                    command.Type = TokenType.Error;
                }
            }

            return true;
        }

        public override ProjectNodeType NodeType
        {
            get
            {
                return ProjectNodeType.CommandBlock;
            }
        }

    }
}
