//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

using System.Collections.Generic;

namespace Whee.WordBuilder.ProjectV2
{
	public interface IProjectSerializer
	{
		int GetIndentationLevel(string indentation);
		Token ReadIndentationToken(IProjectNode node);
        Token ReadTextToken(IProjectNode node);
        Token ReadBlockStarterToken(IProjectNode node);
        Token ReadBlockEnderToken(IProjectNode node);
        Token ReadLineBreakToken(IProjectNode node);
		Token ReadNumericToken(IProjectNode node, ref double value, out bool found);
        Token ReadSquaredBlockToken(IProjectNode node);
        Token ReadRepeatingToken(IProjectNode node, out int repetitions, out string data);
        bool Done {get;}
        void RollBackToken(Token token);
        List<Token> Tokens { get; }
        int Position { get; }
        int LineNumber { get; }
        int LastIndentationLevel { get; }
        int CurrentIndentationLevel { get; }
        Whee.WordBuilder.Helpers.IRandom Random { get; }
        void Warn(string message, IProjectNode node);
		
        //Token ReadToken(TokenType expectedTypes);
        //Token ReadToken(TokenType expectedTypes, int expectedIndentation);
	}
}
