//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Whee.WordBuilder.Helpers;

namespace Whee.WordBuilder.ProjectV2
{
	abstract public class ProjectNodeBase : IProjectNode
	{
		public ProjectNodeBase(IProjectSerializer serializer)
		{
			m_serializer = serializer;
            Index = m_serializer.Position;
		}

		protected IProjectSerializer m_serializer;

		#region IProjectNode implementation
		public int Index { get; set; }
        public int Length { get; set; }

        public IProjectSerializer Serializer { get { return m_serializer; } }
				
		public abstract ProjectNodeType NodeType { get; }

		private List<IProjectNode> m_Children = new List<IProjectNode>();
		public List<IProjectNode> Children {
			get {
				return m_Children;
			}
		}
		
		#endregion

		public ProjectNodeBase ()
		{
		}
	}
}
