//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Whee.WordBuilder.ProjectV2
{
	public enum ProjectNodeType
	{
		Root,
		TokenSetDeclaration, 
		RuleDeclaration,
		StartingRuleDeclaration,
		ColumnDeclaration,
		Command,
		CommandBlock,
        Translation,
		ProblemArea
	}
}
