//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Whee.WordBuilder.ProjectV2
{
	public class StartingRuleNode : ProjectNodeBase		
	{
		public StartingRuleNode (IProjectSerializer serializer) : base(serializer)
		{
			LoadParameters();
		}
		
		public override ProjectNodeType NodeType {
			get {
				return ProjectNodeType.StartingRuleDeclaration;
			}
		}

		private string m_Name;
		public string Name { get { return m_Name; } }
		
		private double m_Amount = 100;
		public int Amount { get { return (int)m_Amount; } }
		
		private void LoadParameters()
		{
			Token name = m_serializer.ReadTextToken(this);
			
			if (name != null)
			{
                name.Type = TokenType.Name;
				m_Name = name.Text;
			}

            Token lineBreak = m_serializer.ReadLineBreakToken(this);

            if (lineBreak == null)
            {
                bool found = false;
                Token amount = m_serializer.ReadNumericToken(this, ref m_Amount, out found);

                if (amount == null && found)
                {
                    m_serializer.Warn(string.Format("Amount specified for starting rule '{0}' was not a number.", m_Name), new ProblemAreaNode(m_serializer.Position));
                }

                lineBreak = m_serializer.ReadLineBreakToken(this);
            }
		}
	}
}
