//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Whee.WordBuilder.ProjectV2
{
	public class Token
	{
        public Token(TokenType type, string text, int offset, int length)
        {
            m_Type = type;
            m_Text = text;
            m_Offset = offset;
            m_Length = length;
        }
        
        public Token(IProjectNode node, TokenType type, string text, int offset, int length, int lineNumber)
		{
            ProjectNode = node;
			m_Type = type;
			m_Text = text;
			m_Offset = offset;
			m_Length = length;
            m_LineNumber = lineNumber;
		}
		
		private TokenType m_Type;
		private string m_Text;
		private int m_Offset;
		private int m_Length;
        private int m_LineNumber;
		
		public string Text { 
			get {
				return m_Text;
			}
		}
		
		public int Offset {
			get {
				return m_Offset;
			}
		}
		
		public int Length {
			get {
				return m_Length;
			}
		}

        public int LineNumber
        {
            get
            {
                return m_LineNumber;
            }
        }
		
		public TokenType Type {
			get {
				return m_Type;
			}
            set
            {
                m_Type = value;
            }
		}

        public IProjectNode ProjectNode
        {
            get;
            set;
        }
	}
}
