//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Whee.WordBuilder.Model.Commands;
using Whee.WordBuilder.ProjectV2;

namespace Whee.WordBuilder.ProjectV2
{
    public class WeightedCommandBlockNode : BlockNodeBase
    {
        public WeightedCommandBlockNode(IProjectSerializer serializer)
            : base(serializer)
        {
        }

        public override bool LoadSingleItem()
        {
            WeightedCommandNode wcn = new WeightedCommandNode(m_serializer);

            if (wcn.Successful)
            {
                Children.Add(wcn);
            }

            return true;
        }

        public override ProjectNodeType NodeType
        {
            get
            {
                return ProjectNodeType.CommandBlock;
            }
        }

    }
}
