//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Gtk;

namespace Whee.WordBuilder.UIHelpers
{
	public class ClipBoardHelper : IClipBoardHelper
	{
		public ClipBoardHelper()
		{
		}
		
		#region IClipBoardHelper implementation
		public void Copy (string data)
		{
			Clipboard cb = Clipboard.Get(Gdk.Selection.Clipboard);
			cb.Text = data.Replace("\r\n", "\n");
		}
		
		public string Paste ()
		{
			Clipboard cb = Clipboard.Get(Gdk.Selection.Clipboard);
			return cb.WaitForText();
		}
		
		#endregion		
	}
}
